### ISSUE TITLE
Update error handling with `thiserror` macro

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-jni#16]
The project currently uses `BDKJNIError` enum for errors and `JNIError` struct to serialize errors to the JNI callers. The [thiserror](https://github.com/dtolnay/thiserror) macro can be used to derive `std::error::Error` trait for `BDKJNIError` errors. It should also be possible to chain `Results` with `.andThen` to simplify and separate json serialization and error handling from the main app logic.

**Comment by thunderbiscuit** [comment]
Closing this now as this library is not maintained anymore in favour of [bdk-android](https://github.com/bitcoindevkit/bdk-kotlin) and [bdk-jvm](https://github.com/bitcoindevkit/bdk-kotlin).
