### ISSUE TITLE
Questions around building library for server-side Kotlin/Java

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-jni#25]
Just wondering how much work it would be to build the library into a `.jar` file that could be used for server-side JVM work.

I was working through a tutorial for ktor and figured I'd try to use `bdk-jni` for it, but then realized we currently only build for the Android platform. I'd be happy to help and learn.

Do you think that's possible slash worthy of time spent on it?

**Comment by afilini** [comment]
Should be pretty easy to do so, the main thing would probably be some cleanup/removal of the android-specific stuff like the android logger

https://github.com/bitcoindevkit/bdk-jni/blob/99f2dfa8a74a7324985bd5ddb10a38afa9ae4b8a/src/lib.rs#L479-L481

**Comment by thunderbiscuit** [comment]
Is that something I should add a line above so it compiles only under certain circumstances/targets? Or do you think I should just work on a specific new branch in my fork and try to build a `.jar`-only version, in which I would just delete all the `android_logger` stuff?

**Comment by afilini** [comment]
Unless there are massive differences I think it definitely makes sense to reuse the same code. I guess in this case you could, for instance, define a `init_log()` function and then implement it differently based on the target:

```rust
#[cfg(target_os="android")]
fn init_log() {
    // ...
}

#[cfg(not(target_os="android"))]
fn init_log() {
    // ...
}
```

I think the `Cargo.toml` dependency is already specified correctly, meaning that it only includes `android_logger` when actually targeting `android`.

**Comment by thunderbiscuit** [comment]
I think we've got this in the works. This issue can be closed. Migrating the discussion of how to do it in #36.
