### ISSUE TITLE
Publish .jar and .aar artifacts to a public maven2 repository

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-jni#32]
https://maven.apache.org/repository/guide-central-repository-upload.html

**Comment by thunderbiscuit** [comment]
Closing this now as this library is not maintained anymore in favour of [bdk-android](https://github.com/bitcoindevkit/bdk-kotlin) and [bdk-jvm](https://github.com/bitcoindevkit/bdk-kotlin).
