### ISSUE TITLE
Building into a jar library

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-jni#36]
This issue is to discuss the process of updating the library to produce a JVM compatible library of `bdk-jni` and to assemble related links.

**Comment by thunderbiscuit** [comment]
@notmandatory and I had the beginnings of this idea fleshed out on [this branch](https://github.com/notmandatory/bdk-jni/tree/feat/build_jar) of his fork.

Another example of this is the [bdk-ffi](https://github.com/notmandatory/bdk-ffi) library.

**Comment by thunderbiscuit** [comment]
I'm trying to see if I can get this started. Looking at your commits @notmandatory. It looks like you had renamed the libraries `bdk-android` and `bdk-jvm`. Is that right?. I really like the distinction. Just a quick question: I see it in the `gradle.build` files, but not in the name of the packages. Is that for a reason (something to do with the common testing maybe?)

I'm not exactly sure but it looks like the code is actually reused between the two so I can see how they might have to be named the same package. Just trying to figure out exactly how this works. Anything you could tell me on that would help.

**Comment by notmandatory** [comment]
I recommend using the example in the [bdk-ffi/bdk-kotlin](https://github.com/notmandatory/bdk-ffi/tree/master/bdk-kotlin) sub project. There is a parent gradle project `bdk-kotlin` with three modules `android`, `jvm`, and `test-fixtures`.  The main kotlin code is in the `jvm` project and brought into the `android` project as a dependency. Both the `android` and `jvm` projects have test dependencies on the `test-fixtures` project, with each one using the same abstract test class but overriding to use their own required logging framework.

**Comment by thunderbiscuit** [comment]
Spent a few hours on this last night and couldn't get it to work. I do think the library was there but the tests not working. Too many pieces of that puzzle all at once. The other thing is I'm not sure if the dependencies and my local setup are creating problems (gradle wrapper, gradle plugin, koltin plugin, kotlin version, JDK version...).

I think I'll try fresh and do very small commits, one by one, and we can discuss as I go.

**Comment by thunderbiscuit** [comment]
So here is my approach:

[ ] 1. Rename `library` module to `android` and `build.sh` to `build-android.sh`. Everything else stays the same. Library should build and publish just as before. 
[ ] 2. Copy `android` module to create `jvm` module. Create a simplified `build-android.sh` file called `build-jvm.sh`. At this point the libraries should be completely independent of each other.
[ ] 3. Remove code in `android` and add dependency on `jvm` module, and migrate tests to a separate project called `test-fixtures`, as per `bdk-ffi`.

**Comment by thunderbiscuit** [comment]
🚀
