### ISSUE TITLE
Integrate the database flush to disk

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-jni#42]
Opening this to keep track of the issue.

**Comment by notmandatory** [comment]
I just realized that the Database.flush() function (https://github.com/bitcoindevkit/bdk/pull/409) isn't yet fully integrated in the `bdk` `Wallet` in v0.11.0. There are a few routes we could take:
1. expose a wallet function to do the flush manually (a bit ugly), 
2. have flush called automatically on wallet operations that need it (could hurt performance)
3. same as 2. with optional flushing selected during wallet creation, so only apps who need it turn it on

Any other ideas?

**Comment by notmandatory** [comment]
I'm thinking now that once https://github.com/bitcoindevkit/bdk/pull/376 is merged we may not need the `flush()` option at all. Will need to test `sqlite` with Android first but according to the docs and the fact that many mobile apps use sqlite already I think it will solve the corrupt DB issue without requiring a flush.
https://www.sqlite.org/howtocorrupt.html

**Comment by thunderbiscuit** [comment]
Closing this now as this library is not maintained anymore in favour of [bdk-android](https://github.com/bitcoindevkit/bdk-kotlin) and [bdk-jvm](https://github.com/bitcoindevkit/bdk-kotlin).
