### ISSUE TITLE
Instructions for downloading the artifacts

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-jni#45]
I'm wondering how folks who cannot build the libraries themselves can download them now that we have the new workflow from @DarthBenro008.

@DarthBenro008 do you mind giving us pointers as to how to do it?

cc: @sunidhi64 & @mbcse

**Comment by DarthBenro008** [comment]
Hey! So there are two ways one can do this:

### Via Release triggered by GitHub Actions (Recommended for stable users)
- This Action is triggered when a person with **write access** on this repository **creates a tag (eg: `v0.3.0`) and pushes** it to master branch
- The Action will automatically create a release with the specified tag
- The release will contain the contents of `Changelog.md`
- The release will automatically have `library.aar` under assets section which can be directly downloaded into your PC with a click.
![image](https://user-images.githubusercontent.com/31009634/125495430-ad8fb2ae-4f64-4abb-bd50-71ac8fcc364f.png)

### Via GitHub Actions Run (Latest master code, not recommended for stable users)
- This Action is triggered for **every push and PR** to the master branch of this repository
- Go to Actions Tab
- Click on the latest run (for eg: https://github.com/bitcoindevkit/bdk-jni/actions/runs/1090685094)
- Click on `android-aar` as shown in the image below
- A zip file containing the builded binary will be downloaded to your PC
- Extract the `.zip` to find `android-release.aar` in the root folder
![image](https://user-images.githubusercontent.com/31009634/128951926-7c9b8ac3-4cf3-42cf-8b21-ecc9e90b328a.png)

Hope this helps 😃 !

**Comment by thunderbiscuit** [comment]
Closing this now as this library is not maintained anymore in favour of [bdk-android](https://github.com/bitcoindevkit/bdk-kotlin) and [bdk-jvm](https://github.com/bitcoindevkit/bdk-kotlin).
