### ISSUE TITLE
Relicensing MIT + Apache

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-jni#46]
This issue is based on a [similar issue] from the LDK project. 

There is an open PR #40 that includes a commit to dual licensing BDK-JNI under [MIT] and [Apache 2.0] instead of only MIT. Both licenses are simple and permissive, making it easy for open source and commercial projects to adopt BDK-JNI. The primary advantages of dual licensing are:

1. the [Apache 2.0] licenses provides additional "patent use" permission
2. most [Rust crates] are dual licensed under MIT and Apache 2.0 
3. the [BDK] project is dual license MIT and Apache 2.0 so will make the license more compatible

To go forward with this change we need anyone who's made significant contributions before to sign off. I've listed all of the folks who show up in `git shortlog` below. If we don't get everyone that may be OK, but we'll need to go back and check that their contributions were relatively minor.

If you're on the below list and agree with this change please add a comment with "I hereby re-license my previous contributions to BDK under [Apache 2.0] in addition to the existing [MIT] license." 

[similar issue]: https://github.com/rust-bitcoin/rust-lightning/issues/659
[Apache 2.0]: https://choosealicense.com/licenses/apache-2.0/
[MIT]: https://choosealicense.com/licenses/mit/
[Rust crates]: https://choosealicense.com/community/
[LDK]: https://github.com/rust-bitcoin/rust-lightning
[BDK]: https://github.com/bitcoindevkit/bdk

- [x] @afilini 
- [x] @DarthBenro008
- [x] @lvaccaro 
- [x] @notmandatory 
- [x] @thunderbiscuit

**Comment by notmandatory** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.

**Comment by thunderbiscuit** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.

**Comment by DarthBenro008** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.

**Comment by lvaccaro** [comment]
I hereby re-license my previous contributions to BDK under Apache 2.0 in addition to the existing MIT license.

**Comment by notmandatory** [comment]
Completed with PR #40
