### ISSUE TITLE
Where is BDK-JNI database

### ISSUE THREAD

**Issue by mbcse** [bitcoindevkit/bdk-jni#47]
I wanted to know where can I find the sled database which stores the descriptors 
cc @thunderbiscuit

**Comment by thunderbiscuit** [comment]
I'm not sure if we can get direct access to those (I don't think we can unfortunately, because they're not exposed by the library).

**Comment by notmandatory** [comment]
@thunderbiscuit is right the sled DB isn't directly accessible through the JNI API, but you can find the sled data files in the standard android data location.

**Comment by thunderbiscuit** [comment]
Closing this now as this library is not maintained anymore in favour of [bdk-android](https://github.com/bitcoindevkit/bdk-kotlin) and [bdk-jvm](https://github.com/bitcoindevkit/bdk-kotlin).
